live_config_reload = true

[colors.normal]
black = "0x151515"
blue = "0x6c99ba"
cyan = "0x7dd5cf"
green = "0x7ACC52"
magenta = "0x9e4e85"
red = "0xac4142"
white = "0xd0d0d0"
yellow = "0xe5b566"

[colors.primary]
background = "0x202020"
foreground = "0xd0d0d0"

[font]
size = 13.0

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.94

[window.dimensions]
columns = 108
lines = 32

[window.padding]
x = 16
y = 14
