#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# window rules
yabai -m rule --add app="^(Calculator|System Settings|Archive Utility|Finder|Numi)$" manage=off

# global settings
config=(
    mouse_follows_focus          off
    focus_follows_mouse          on
    window_origin_display        default
    window_placement             second_child
    window_zoom_persist          on
    window_shadow                on
    window_animation_duration    0.0
    window_animation_frame_rate  120
    window_opacity_duration      0.0
    active_window_opacity        1.0
    normal_window_opacity        0.90
    window_opacity               off
    insert_feedback_color        0xffd75f5f
    split_ratio                  0.50
    split_type                   auto
    auto_balance                 off
    top_padding                  12
    bottom_padding               12
    left_padding                 12
    right_padding                12
    window_gap                   10
    layout                       bsp
    mouse_modifier               alt
    mouse_action1                move
    mouse_action2                resize
    mouse_drop_action            mo
)
yabai -m config "${config[@]}"

# sketchybar offset 
# yabai -m config external_bar all:$(sketchybar --query bar | jq ".height, .y_offset" | awk '{s+=$1} END {print s}'):0
# yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

echo "yabai configuration loaded.."
